/////////////////////////////////////////////////////////////
//
// Helpcode.h
//
// Various help context IDs for EasyB
//
/////////////////////////////////////////////////////////////


//
// Message Box help IDs
//
//#define HIDT_CANT_OPEN_FILE		2000
#define HIDT_INTRODUCTION			3000
#define HIDT_QUICK_START			3100

// sepcial sections
#define HIDT_FAQ_CARDS_CROWDING		5100

//
// Dialogs
//
//#define HIDX_DISPLAY_OPTIONS 		8000
//#define HIDX_PAGE_SETUP      		8100

//
// Other
//
#define MAIN_INDEX				9000
#define WHATS_NEW_INDEX			9005
#define RULES_INDEX				9010
#define MENU_INDEX				9020
//#define GAME_PLAY_INDEX			9030
#define MISC_TOPICS_INDEX		9040
#define GLOSSARY_INDEX			9050
#define DIALOGS_INDEX			9100
#define CONVENTIONS_INDEX		9200
#define FAQ_INDEX				9300
#define WIZARDS_INDEX			9400

// Individual dialogs
#define DIALOG_FILE_OPEN			10100
#define DIALOG_FILE_SAVE_AS			10200
#define DIALOG_FILE_SAVE_OPTIONS	10210
#define DIALOG_FILE_PROPERTIES		10220
#define DIALOG_HISTORY				10400
//#define DIALOG_ANALYSIS_WINDOW		10600
#define DIALOG_FILE_COMMENTS		10700
#define DIALOG_BIDDING				10800
#define DIALOG_BIDDING_SMALL		10801
#define DIALOG_CARD_LAYOUT			10900
#define DIALOG_GAME_REVIEW			11000
#define DIALOG_SELECT_HAND			11100
#define DIALOG_SELECT_DEALER		11101
#define DIALOG_DEAL_NUMBER			11200
#define DIALOG_HAND_FINISHED		11300

// Bid options property pages
#define DIALOG_BID_OPTIONS_CONFIG_PAGE		12000
#define DIALOG_BID_OPTIONS_GENERAL_PAGE		12001
#define DIALOG_BID_OPTIONS_2BIDS_PAGE		12002
#define DIALOG_BID_OPTIONS_NT_RANGE_PAGE	12003
#define DIALOG_BID_OPTIONS_MISC_PAGE		12004
#define DIALOG_BID_OPTIONS_OPENING_PAGE		12005

// Deal options property pages
#define DIALOG_DEAL_OPTIONS_POINTS_PAGE		12100
#define DIALOG_DEAL_OPTIONS_MINORS_PAGE		12101
#define DIALOG_DEAL_OPTIONS_MAJORS_PAGE		12102
#define DIALOG_DEAL_OPTIONS_NO_TRUMPS_PAGE	12103
#define DIALOG_DEAL_OPTIONS_SLAM_PAGE		12104
#define DIALOG_DEAL_OPTIONS_MISC_PAGE		12105

// Display options property pages
#define DIALOG_DISPLAY_OPTIONS_SUITS_PAGE		12200
#define DIALOG_DISPLAY_OPTIONS_CARDS_PAGE		12201
#define DIALOG_DISPLAY_OPTIONS_CARDBACKS_PAGE	12202
#define DIALOG_DISPLAY_OPTIONS_DIALOGS_PAGE		12203
#define DIALOG_DISPLAY_OPTIONS_FONTS_PAGE		12204
#define DIALOG_DISPLAY_OPTIONS_MISC_PAGE		12205

// Game options property pages
#define DIALOG_GAME_OPTIONS_INTERFACE_PAGE	12300
#define DIALOG_GAME_OPTIONS_MECHANICS_PAGE	12301
#define DIALOG_GAME_OPTIONS_COUNTING_PAGE	12302
#define DIALOG_GAME_OPTIONS_SCORING_PAGE	12303
#define DIALOG_GAME_OPTIONS_FILES_PAGE		12304
#define DIALOG_GAME_OPTIONS_GIB_PAGE		12305

// Debug status property pages
#define DIALOG_STATUS_PLAY_PLAN_PAGE		12500
#define DIALOG_STATUS_CARD_LOCATIONS_PAGE	12501
#define DIALOG_STATUS_HOLDINGS_PAGE			12502
#define DIALOG_STATUS_GIB_MONITOR_PAGE		12503

// Program Config Wizard pages
#define WIZARD_PROG_CONFIG_WELCOME_PAGE		12601
#define WIZARD_PROG_CONFIG_HELPLEVEL_PAGE	12602
#define WIZARD_PROG_CONFIG_VIEWOPTS_PAGE	12603
#define WIZARD_PROG_CONFIG_SUITS_PAGE		12604
#define WIZARD_PROG_CONFIG_GAMEOPTS_PAGE	12605
#define WIZARD_PROG_CONFIG_PAUSES_PAGE		12606
#define WIZARD_PROG_CONFIG_BIDSTYLE_PAGE	12607
#define WIZARD_PROG_CONFIG_FINISH_PAGE		12608
